### ISSUE TITLE
Need more context on errors

### ISSUE THREAD

**Issue by doanac** [foundriesio/ci-scripts#78]
https://github.com/foundriesio/ci-scripts/blob/1cd03740e958627ba58992b2a564f45e14918713/factory-containers/assemble-system-image#L304

That looks nice to try and hide things. But it winds up producing a message like this:
~~~
ERROR:System Image Assembler:Failed to assemble a system image(s): 'image-file'
~~~

I'm assuming there was some KeyError thrown somewhere. But lacking the exception (and really stack trace) makes things like this hard to dig into.

**Comment by doanac** [comment]
I also realize we need to sys.exit(1) here or the CI job passes rather than fails

**Comment by mike-sul** [comment]
@doanac makes sense, will fix and improve it.

**Comment by mike-sul** [comment]
> I'm assuming there was some KeyError thrown somewhere. But lacking the exception (and really stack trace) makes things like this hard to dig into.

'image-file' attribute is missing in Target json, it means that a given Target's image was built before I made this change https://github.com/foundriesio/ci-scripts/blob/master/lmp/customize-target#L107

**Comment by mike-sul** [comment]
> I also realize we need to sys.exit(1) here or the CI job passes rather than fails

This one has been already fixed.

**Comment by mike-sul** [comment]
Using `logger.exception()` will produce something like the following:


`|  ERROR:System Image Assembler:'image-file'
|  Traceback (most recent call last):
|    File "/ci-scripts/factory-containers/assemble-system-image", line 406, in <module>
|      assemble_image_for_targets(targets, args.app_image_dir, args.out_image_dir, args.token)
|    File "/ci-scripts/factory-containers/assemble-system-image", line 294, in assemble_image_for_targets
|      wic_image = get_system_image_from_ci(target, token)
|    File "/ci-scripts/factory-containers/assemble-system-image", line 65, in get_system_image_from_ci
|      image_filename = target['custom']['image-file']
|  KeyError: 'image-file'
|--
`

I guess it's good enough.

**Comment by mike-sul** [comment]
@doanac Added it to this PR https://github.com/foundriesio/ci-scripts/pull/80/files#diff-60d1ed4976ea0a6246ce6440ab41b9dfR407
