### ISSUE TITLE
Give undocumented vars their own definitions/directives in ci-scripts

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/ci-scripts#88]
There are some variables that are important and should not have to be set via `lmp.params`, such as `IMAGES` and `DOCKER_SECRETS`. For example, if we do not define `IMAGES` then it will produce an error. My understanding is that `lmp.params` is intended to be a user-configured section, with only user additions. So it makes sense to separate these two, as currently we set:

```
lmp:
  params:
    IMAGE: lmp-factory-image
```

which encroaches upon the user's space. The same will be true if we introduce other variables here by default in future, instead of creating new directives for these variables.

**Comment by doanac** [comment]
making progress here - https://git.foundries.io/development/cloudplatforms/infrastructure/repoz/merge_requests/22
